/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Tue Mar 14 17:44:11 2023"
#define BUILD_TIME (1678837451UL)

#define VERSION_NUMBER 0x03060700UL
#define VERSION_FEATURES 0x00060000UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211c517dUL
#define VERSION_SANITY2 0x148c24958UL
#define VERSION_SANITY3 0x00028000UL

#define VERSION_STRING "3.6.7-0"
#define VERSION_ID \
 "MacOSX NetHack Version 3.6.7-0 post-release - last build Tue Mar 14 17:44:11 2023."
#define COPYRIGHT_BANNER_C \
 "         Version 3.6.7-0 MacOSX post-release, built Mar 14 17:44:11 2023."

#define NETHACK_GIT_SHA "557e18611a860fa17bbb8e5dbfd37b96c9304fe1"
#define NETHACK_GIT_BRANCH "NetHack-3.6"
