/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Mon Jan 30 04:13:08 2023"
#define BUILD_TIME (1675051988UL)

#define VERSION_NUMBER 0x03060600UL
#define VERSION_FEATURES 0x00060000UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211c517dUL
#define VERSION_SANITY2 0x148c24958UL
#define VERSION_SANITY3 0x00028000UL

#define VERSION_STRING "3.6.6"
#define VERSION_ID \
 "Unix NetHack Version 3.6.6 - last build Mon Jan 30 04:13:08 2023."
#define COPYRIGHT_BANNER_C \
 "         Version 3.6.6 Unix, built Jan 30 04:13:08 2023."

